config/routes.rb
Rails.application.routes.draw do
  resources :carts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :offlinestoredetails
  resources :offlinestores
  resources :onlinestores

  resources :categories
  resources :products
  resources :roles
    post 'products/addtocart'
root to: 'home#index'

devise_for :users



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

    has_attached_file :pimage, :styles => { :medium => "200x200>", :thumb => "50x50>" }, :default_url => "medium/default_image.png"
    validates_attachment_content_type :pimage, content_type: /\Aimage\/.*\z/
    validates_presence_of :title, :description, :price, :status, :shipping
    belongs_to :category
    has_many :offlinestoredetails, :through => :offlinestores

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :active_add_to_cart!, only: [:addtocart]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def addtocart
        @product = Product.find(params[:id])
      @cart = Cart.find_by(product_id: params[:id], user_id: session['user'])


      if @cart.nil?
        @cart = Cart.new(product_id: params[:id], user_id: session['user'])
        if @cart.save
          message = 'Added Product Successfully in your Cart'
        else
          message = 'Something wrong while Adding this Product in your Cart'
        end

      else
    message = 'You already Added this Product in your Cart'
  end
   respond_to do |format|
        format.html { redirect_to carts_path(id: @product.id), flash: { notice: message } }
        format.json { render :show, location: @product }
      end
    end








  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :status, :shipping ,:pimage,:category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :shipping %>
    <%= f.text_field :shipping %>
  </div>
  <div class="field">
    <%= f.label :pimage %>
    <%= f.file_field :pimage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th>Shipping</th>
      <th>Product Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>

        <td><a href="<%= product_path(product.id) %>"><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.status %></td>
        <td><%= product.shipping %></td>
        <td><%= image_tag product.pimage.url(:thumb) %></td>
        <!--<td><%= link_to 'Show', product %></td>-->
        <!--<td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Product', new_product_path %>-->

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>Shipping:</strong>
  <%= @product.shipping %>
</p>

<p>
  <strong>Product Image:</strong>
  <%= image_tag @product.pimage.url(:thumb) %>
</p>

<!--<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>-->

<%= link_to "Add to Cart",products_addtocart_path(:id => @product), :method => 'post', :class => 'btn btn-primary' %>